services:
  bondle-front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://bondle-back:4112
        - VITE_ENV=prod
    container_name: bondle-front
    restart: unless-stopped
    ports:
      - "5111:80"
    networks:
      - proxy

networks:
  proxy:
    external: true
